# Generated by Django 6.0.4 on 2026-05-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_seat_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_bookend',
            new_name='is_booked',
        ),
    ]
