# Generated by Django 6.0.4 on 2026-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_is_bookend_seat_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
