# Generated by Django 6.0.4 on 2026-05-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='passanger_age',
            new_name='passenger_age',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='passanger_name',
            new_name='passenger_name',
        ),
    ]
